// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWDk2GGWPlgru9Q35hVr97O6-vQNMaabY',
    appId: '1:841859634198:web:ce319fbc508e18bdbf5137',
    messagingSenderId: '841859634198',
    projectId: 'flutter-fb-trial',
    authDomain: 'flutter-fb-trial.firebaseapp.com',
    storageBucket: 'flutter-fb-trial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlrSF6-_7udr6ZVWJq2snk7kyMpmqJbQ',
    appId: '1:841859634198:android:1d22d17a9bb36cfbbf5137',
    messagingSenderId: '841859634198',
    projectId: 'flutter-fb-trial',
    storageBucket: 'flutter-fb-trial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFMc-0SE9Osyi9qFANMkVTMpzeCnFaBlA',
    appId: '1:841859634198:ios:34c89fabed64c8f7bf5137',
    messagingSenderId: '841859634198',
    projectId: 'flutter-fb-trial',
    storageBucket: 'flutter-fb-trial.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
